// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="GET_SIGNAL,hls_ip_2019_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.241000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=37,HLS_SYN_LUT=308,HLS_VERSION=2019_2}" *)

module GET_SIGNAL (
        i_clk,
        i_rst,
        i_weight,
        i_human_control,
        i_speed,
        i_ir_sensor,
        o_speed_control,
        o_state,
        o_alarm_signal,
        o_f_ham,
        o_f_day,
        o_destination,
        ap_rst
);


input   i_clk;
input   i_rst;
input  [11:0] i_weight;
input   i_human_control;
input  [8:0] i_speed;
input  [4:0] i_ir_sensor;
output  [2:0] o_speed_control;
output  [2:0] o_state;
output  [1:0] o_alarm_signal;
output  [8:0] o_f_ham;
output  [8:0] o_f_day;
output   o_destination;
input   ap_rst;

reg[2:0] o_speed_control;
reg[2:0] o_state;
reg[1:0] o_alarm_signal;
reg[8:0] o_f_ham;
reg[8:0] o_f_day;
reg o_destination;

wire   [0:0] GET_SIGNAL_ssdm_t_load_fu_144_p1;
wire   [3:0] ap_CS_fsm;
wire   [1:0] call_ln41_GET_SIGNAL_alarm_signal_fu_88_o_alarm_signal;
wire    call_ln41_GET_SIGNAL_alarm_signal_fu_88_o_alarm_signal_ap_vld;
wire   [2:0] grp_GET_SIGNAL_control_speed_fu_116_o_speed_control;
wire    grp_GET_SIGNAL_control_speed_fu_116_o_speed_control_ap_vld;
wire   [2:0] grp_GET_SIGNAL_control_speed_fu_116_o_state;
wire    grp_GET_SIGNAL_control_speed_fu_116_o_state_ap_vld;
wire   [8:0] grp_GET_SIGNAL_control_speed_fu_116_o_f_ham;
wire    grp_GET_SIGNAL_control_speed_fu_116_o_f_ham_ap_vld;
wire   [8:0] grp_GET_SIGNAL_control_speed_fu_116_o_f_day;
wire    grp_GET_SIGNAL_control_speed_fu_116_o_f_day_ap_vld;
wire    grp_GET_SIGNAL_control_speed_fu_116_o_destination;
wire    grp_GET_SIGNAL_control_speed_fu_116_o_destination_ap_vld;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state4;

GET_SIGNAL_alarm_signal call_ln41_GET_SIGNAL_alarm_signal_fu_88(
    .ap_clk(i_clk),
    .ap_rst(ap_rst),
    .i_weight(i_weight),
    .o_alarm_signal(call_ln41_GET_SIGNAL_alarm_signal_fu_88_o_alarm_signal),
    .o_alarm_signal_ap_vld(call_ln41_GET_SIGNAL_alarm_signal_fu_88_o_alarm_signal_ap_vld)
);

GET_SIGNAL_control_speed grp_GET_SIGNAL_control_speed_fu_116(
    .ap_clk(i_clk),
    .ap_rst(ap_rst),
    .i_rst(i_rst),
    .i_weight(i_weight),
    .i_human_control(i_human_control),
    .i_speed(i_speed),
    .i_ir_sensor(i_ir_sensor),
    .o_speed_control(grp_GET_SIGNAL_control_speed_fu_116_o_speed_control),
    .o_speed_control_ap_vld(grp_GET_SIGNAL_control_speed_fu_116_o_speed_control_ap_vld),
    .o_state(grp_GET_SIGNAL_control_speed_fu_116_o_state),
    .o_state_ap_vld(grp_GET_SIGNAL_control_speed_fu_116_o_state_ap_vld),
    .o_f_ham(grp_GET_SIGNAL_control_speed_fu_116_o_f_ham),
    .o_f_ham_ap_vld(grp_GET_SIGNAL_control_speed_fu_116_o_f_ham_ap_vld),
    .o_f_day(grp_GET_SIGNAL_control_speed_fu_116_o_f_day),
    .o_f_day_ap_vld(grp_GET_SIGNAL_control_speed_fu_116_o_f_day_ap_vld),
    .o_destination(grp_GET_SIGNAL_control_speed_fu_116_o_destination),
    .o_destination_ap_vld(grp_GET_SIGNAL_control_speed_fu_116_o_destination_ap_vld)
);

always @ (posedge i_clk) begin
    if ((call_ln41_GET_SIGNAL_alarm_signal_fu_88_o_alarm_signal_ap_vld == 1'b1)) begin
        o_alarm_signal <= call_ln41_GET_SIGNAL_alarm_signal_fu_88_o_alarm_signal;
    end
end

always @ (posedge i_clk) begin
    if ((grp_GET_SIGNAL_control_speed_fu_116_o_destination_ap_vld == 1'b1)) begin
        o_destination <= grp_GET_SIGNAL_control_speed_fu_116_o_destination;
    end
end

always @ (posedge i_clk) begin
    if ((grp_GET_SIGNAL_control_speed_fu_116_o_f_day_ap_vld == 1'b1)) begin
        o_f_day <= grp_GET_SIGNAL_control_speed_fu_116_o_f_day;
    end
end

always @ (posedge i_clk) begin
    if ((grp_GET_SIGNAL_control_speed_fu_116_o_f_ham_ap_vld == 1'b1)) begin
        o_f_ham <= grp_GET_SIGNAL_control_speed_fu_116_o_f_ham;
    end
end

always @ (posedge i_clk) begin
    if ((grp_GET_SIGNAL_control_speed_fu_116_o_speed_control_ap_vld == 1'b1)) begin
        o_speed_control <= grp_GET_SIGNAL_control_speed_fu_116_o_speed_control;
    end
end

always @ (posedge i_clk) begin
    if ((grp_GET_SIGNAL_control_speed_fu_116_o_state_ap_vld == 1'b1)) begin
        o_state <= grp_GET_SIGNAL_control_speed_fu_116_o_state;
    end
end

assign GET_SIGNAL_ssdm_t_load_fu_144_p1 = 1'd0;

assign ap_CS_fsm = 4'd0;

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

endmodule //GET_SIGNAL
